### PR TITLE
Improved upon the website UI and fixed some typos

### PR DESCRIPTION
**Pull request by gayatri-p**
Hey! As the title suggests, I have made some UI improvements and also made sure the website works on smaller screens. I hope the website looks cleaner and more polished now.
Oh and also fixed a few typos along the way.

Screenshot preview of the UI changes: [i.imgur.com/3HkjIfo.png](https://i.imgur.com/3HkjIfo.png)

### CODE REVIEW

**Comment by gayatri-p** [comment]
Screenshot previewof the UI changes: [i.imgur.com/3HkjIfo.png](https://i.imgur.com/3HkjIfo.png)

**Comment by Oliv95** [comment]
Hi @gayatri-p 

Thank you for the PR

I tried out the changes on firefox and it looks a bit off, could you doublecheck that it looks good on all major browsers and I will merge your changes

firefox

**Comment by gayatri-p** [comment]
Thanks for the feedback @Oliv95 .

I have added browser support and it should now work for all browsers (I hope). It has been tested with latest versions of Chrome, Firefox, Opera and Edge.

Anyway, you can check it out here: [gayatri-p.github.io/linusQuoter/website/](https://gayatri-p.github.io/linusQuoter/website/)

**Comment by Oliv95** [comment]
@gayatri-p  Look good, I will merge and deploy the changes

Thank you again for the PR :+1:

**Pull request merged**
